version: '3.8'

services:
  db:
    image: postgres:16.0
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - gc_test_db:/var/lib/postgresql/data
    env_file:
      - .env.postgres
    networks:
      - gc

  app:
    build: .
    restart: always
    command: sh -c "alembic upgrade heads && uvicorn main:gc_test_app --host 0.0.0.0"
    ports:
      - "8000:8000"
    volumes:
      - .:/server
    depends_on:
      - db
    networks:
      - gc


networks:
  gc:
    driver: bridge

volumes:
  gc_test_db: {}
