version: '3.8'

services:
  db:
    image: postgres:16.0
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - gc_test_db:/var/lib/postgresql/data
    env_file:
      - .env.postgres.local

volumes:
  gc_test_db: {}
